# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.2
loom_version=1.14-SNAPSHOT

# Mod Properties
maven_group=com.mgen256
mod_id=additional_lights
mod_name=Additional Lights
mod_license=MIT License
mod_version=2.1.14
mod_authors=mgen256

# Dependencies
fabric_version=0.139.5+1.21.11
