org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.4
parchment_mappings_version=2024.12.07

minecraft_version=1.21.4
minecraft_version_range=[1.21.4, 1.22)
neo_version=21.4.11-beta
neo_version_range=[21.4.0-beta,)
loader_version_range=[4,)

mod_id=additional_lights
mod_name=Additional Lights
mod_license=MIT License
mod_version=2.1.11
mod_group_id=additional_lights
mod_authors=mgen256
mod_description=