# ----- GC / Performance -----
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
org.gradle.configuration-cache=true
org.gradle.warning.mode=summary

# ----- Shared Minecraft / mod metadata -----
mod_version=3.1.0

# NeoForge
# Dependency versions are defined in libs.versions.toml
# NeoForge-specific version ranges, etc.
minecraft_version_range=[26.1,26.2)
neoforge_version_range=[26.1.2.0-beta,)

# Fabric

# Shared mod metadata
mod_id=additional_lights
mod_name=Additional Lights
mod_license=MIT License
mod_authors=mgen256
mod_description=Adds various lighting blocks
pythonPath=.venv\\Scripts\\python.exe
